In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import os
import pandas as pd
import numpy as np

# Get Data

In [2]:
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [3]:
path = kagglehub.dataset_download("kazanova/sentiment140")

Downloading to /root/.cache/kagglehub/datasets/kazanova/sentiment140/2.archive...

100%|██████████| 80.9M/80.9M [00:00<00:00, 110MB/s]

Extracting files...

In [4]:
csv_path = os.path.join(path, "training.1600000.processed.noemoticon.csv")

In [5]:
sent140 = pd.read_csv(csv_path, encoding="latin-1", header=None)

In [6]:
sent140.columns

Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [7]:
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")

Downloading to /root/.cache/kagglehub/datasets/snap/amazon-fine-food-reviews/2.archive...

100%|██████████| 242M/242M [00:01<00:00, 138MB/s]

Extracting files...

In [8]:
csv_path=os.path.join(path,"Reviews.csv")

In [9]:
food=pd.read_csv(csv_path)

In [10]:
sent140.head()

,0,1,2,3,4,5
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [11]:
food.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

 Columns uniques

*   Score: 1 -> 5
*   HelpfulnessNumerator: 1 -> 808
*   HelpfulnessDenominator: 1 -> 815

# Encoding

## TFIDF

In [ ]:
!pip install rank_bm25

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from rank_bm25 import BM25Okapi

Collecting rank_bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rank_bm25) (2.0.2)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Installing collected packages: rank_bm25
Successfully installed rank_bm25-0.2.2

In [13]:
food["Summary"] = food["Summary"].fillna("Not Available")

In [14]:
tfidf=TfidfVectorizer(stop_words='english',
                      max_features=5000,
                      min_df=5)

food_tfidf=tfidf.fit_transform(food['Summary'])

In [15]:
tfidf_df = pd.DataFrame(food_tfidf.toarray(), columns=tfidf.get_feature_names_out())

In [16]:
print("Feature names:", tfidf.get_feature_names_out())
print("Dense matrix shape:", food_tfidf.shape)
feature_names=tfidf.get_feature_names_out()

Feature names: ['00' '000' '10' ... 'zotz' 'zuke' 'zukes']
Dense matrix shape: (568454, 5000)

In [17]:
doc_index = 0

scores = food_tfidf[doc_index].toarray()[0]

word_scores = pd.Series(scores, index=feature_names)

In [18]:
top_words = word_scores.sort_values(ascending=False).head(100)

In [19]:
top_word_vectors=list(top_words.index[0:5])

In [20]:
tfidf_df[top_word_vectors]

         quality      food       dog      good  pizza
0       0.596823  0.506769  0.504101  0.364512    0.0
1       0.000000  0.000000  0.000000  0.000000    0.0
2       0.000000  0.000000  0.000000  0.000000    0.0
3       0.000000  0.000000  0.000000  0.000000    0.0
4       0.000000  0.000000  0.000000  0.000000    0.0
...          ...       ...       ...       ...    ...
568449  0.000000  0.000000  0.000000  0.000000    0.0
568450  0.000000  0.000000  0.000000  0.000000    0.0
568451  0.000000  0.000000  0.000000  0.000000    0.0
568452  0.000000  0.000000  0.000000  0.000000    0.0
568453  0.000000  0.000000  0.000000  0.000000    0.0

[568454 rows x 5 columns]

## BM25

In [21]:
food.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [22]:
# bm25 with split
bm25 = BM25Okapi(food["Summary"].apply(lambda x: x.split(" ")))

In [23]:
query = "good"
tokenized_query = query.split(" ")
doc_scores = bm25.get_scores(tokenized_query)

In [24]:
good_num=bm25.get_top_n(tokenized_query, food["Summary"], n=10)

In [25]:
good_num

['good good',
 'good good',
 'good good',
 'good good',
 'good good',
 'good good',
 'good good',
 'good good',
 'good good',
 'good good soup!']

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
df=food[:10_000]

In [28]:
tokenized_corpus = [doc.lower().split() for doc in df['Text']]

query = "excellent dark coffee"
query_tokens = query.lower().split()

In [31]:
count_vec = CountVectorizer()
count_matrix = count_vec.fit_transform(df['Text']).toarray()
vocab = count_vec.get_feature_names_out()

q_indices = [count_vec.vocabulary_[word] for word in query_tokens if word in count_vec.vocabulary_]
count_scores = np.sum(count_matrix[:, q_indices], axis=1)

tfidf_vec = TfidfVectorizer(norm='l2')
tfidf_matrix = tfidf_vec.fit_transform(df['Text']).toarray()
query_vec = tfidf_vec.transform([query]).toarray()[0]
tfidf_scores = np.dot(tfidf_matrix, query_vec)

bm25 = BM25Okapi(tokenized_corpus, k1=1.5, b=0.75)
bm25_scores = bm25.get_scores(query_tokens)

In [32]:
df['Count_Score'] = count_scores
df['TFIDF_Score'] = np.round(tfidf_scores, 4)
df['BM25_Score'] = np.round(bm25_scores, 4)

/tmp/ipykernel_10059/397437228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Count_Score'] = count_scores
/tmp/ipykernel_10059/397437228.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TFIDF_Score'] = np.round(tfidf_scores, 4)
/tmp/ipykernel_10059/397437228.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BM25_Score'] = np.round(bm25_scores, 4)

In [33]:
# Print a structured matrix comparing results
print(f"{'Review Snippet':<45} | {'Count':<5} | {'TF-IDF':<7} | {'BM25':<7}")
print("-" * 80)
for idx, row in df.iterrows():
    snippet = row['Text'] if len(row['Text']) < 43 else row['Text'][:40] + "..."
    print(f"{snippet:<45} | {row['Count_Score']:<5} | {row['TFIDF_Score']:<7} | {row['BM25_Score']:<7}")

Streaming output truncated to the last 5000 lines.
I thought I'd try the multi-pack to see ...   | 0     | 0.0     | 0.0
i just started the paleo diet and i love...   | 0     | 0.0     | 0.0
I've been Paleo for six months, as has m...   | 0     | 0.0     | 0.0
I bought a 40 sampler pack from the cave...   | 0     | 0.0     | 0.0
Formula itself is great. Works wonders f...   | 0     | 0.0     | 0.0
With all of the choices of things to dri...   | 2     | 0.0907  | 4.0885
This may not be the best tasting thing I...   | 2     | 0.0447  | 1.4049
Let me preface this by saying I purchase...   | 0     | 0.0     | 0.0
I love using generous amounts of vinegar...   | 0     | 0.0     | 0.0
I bought this drink locally and I have t...   | 0     | 0.0     | 0.0
This is the best ever.  Just add HOT wat...   | 0     | 0.0     | 0.0
<a href="http://www.amazon.com/gp/produc...   | 1     | 0.067   | 4.0548
We use these for our daughter for a few ...   | 0     | 0.0     | 0.0
These are really excellent breakfast bar...   | 1     | 0.0906  | 4.2588
The flavor of the fruit enclosed is outs...   | 0     | 0.0     | 0.0
I keep a box of these in my desk at work...   | 0     | 0.0     | 0.0
my boys have been eating these for over ...   | 0     | 0.0     | 0.0
I bought these bars for several years at...   | 0     | 0.0     | 0.0
Whole family likes these.  Tasty but not...   | 0     | 0.0     | 0.0
barbara's yogurt bars are okay.  i found...   | 0     | 0.0     | 0.0
My son has been eating these for the las...   | 0     | 0.0     | 0.0
This product was a big disappointment.  ...   | 0     | 0.0     | 0.0
These aren't as good as other bars of th...   | 0     | 0.0     | 0.0
Good product! good price  fast shipping ...   | 0     | 0.0     | 0.0
Looked like a good deal, so I ordered th...   | 0     | 0.0     | 0.0
I couldn't find this product in the stor...   | 0     | 0.0     | 0.0
As an avid rice cracker fan, I've tried ...   | 0     | 0.0     | 0.0
Our Corgi loves all sizes, shapes, and f...   | 0     | 0.0     | 0.0
When I received this product it was old ...   | 0     | 0.0     | 0.0
most of the nuts in these bags were so o...   | 0     | 0.0     | 0.0
I did not even receive the correct produ...   | 0     | 0.0     | 0.0
<a href="http://www.amazon.com/gp/produc...   | 0     | 0.0     | 0.0
I would agree with the other poor rating...   | 0     | 0.0     | 0.0
I recommand this product. My childrens (...   | 0     | 0.0     | 0.0
I've tried many different brands of Virg...   | 0     | 0.0     | 0.0
First of all, there are two kinds of pap...   | 0     | 0.0     | 0.0
I was so pleased with this purchase. A g...   | 0     | 0.0     | 0.0
Not only is the sweetener great in coffe...   | 1     | 0.0487  | 2.6546
I adore using this very vanilla bean pas...   | 0     | 0.0     | 0.0
Enfamil Premium Lipil Formula is the sam...   | 1     | 0.0155  | 1.164
I wish I found the plastic refill packs ...   | 0     | 0.0     | 0.0
Alot of moms like me like this item beca...   | 0     | 0.0     | 0.0
no gas for baby, no extra bubbles when y...   | 0     | 0.0     | 0.0
We had to move to formula when our baby ...   | 0     | 0.0     | 0.0
Our Baby loves it. And Amazon is very re...   | 0     | 0.0     | 0.0
I read other reviews before buying and t...   | 0     | 0.0     | 0.0
Go to Costco, and you can buy lower than...   | 0     | 0.0     | 0.0
Be careful when odering this, because th...   | 0     | 0.0     | 0.0
If one reads this products ingredients t...   | 0     | 0.0     | 0.0
Have tried a few different peanut brittl...   | 0     | 0.0     | 0.0
These were rancid upon receipt.  Terribl...   | 0     | 0.0     | 0.0
I like that these are organic and don't ...   | 0     | 0.0     | 0.0
I have been buying  new Morning Graham C...   | 0     | 0.0     | 0.0
My husband has to limit the amount of su...   | 0     | 0.0     | 0.0
I rarely want to eat much when I first a...   | 2     | 0.0587  | 0.0
My children will only eat healthy produc...   | 0     | 0.0     | 0.0
These crackers are terrific, and they ar...   | 0     | 0.0     | 0.0
These are very good, they were a great p...   | 0     | 0.0     | 0.0
I was quite surprised to find that Socia...   | 0     | 0.0     | 0.0
I felt ripped off. The photo clearly sho...   | 0     | 0.0     | 0.0
Wow I heard of this candy but could neve...   | 0     | 0.0     | 0.0
I absolutely love these! Seven of these ...   | 0     | 0.0     | 0.0
I love the 34 degree cracked peppercorn,...   | 0     | 0.0     | 0.0
Is that these are 60 calories per servin...   | 0     | 0.0     | 0.0
This soup is good. I really love this br...   | 0     | 0.0     | 0.0
First, I agree with J. Bishop's (Houston...   | 0     | 0.0     | 0.0
If you love vegetable soup you should li...   | 0     | 0.0     | 0.0
I enjoyed this soup.  It was flavorful w...   | 0     | 0.0     | 0.0
Tortilla soup is one of my favorite soup...   | 0     | 0.0     | 0.0
First off, there is a difference when yo...   | 0     | 0.0     | 0.0
This brand is a little hard to find in s...   | 0     | 0.0     | 0.0
If you like coconut water, then you will...   | 0     | 0.0     | 0.0
this is great coconut water and there is...   | 0     | 0.0     | 0.0
Pretty close to the taste of a freshly o...   | 0     | 0.0     | 0.0
As far as taste goes, this is the best c...   | 1     | 0.0091  | 0.8087
This is my favorite coconut water! Havin...   | 0     | 0.0     | 0.0
I had coconut trees growing in my backya...   | 0     | 0.0     | 0.0
IMHO. There is simply not a better bever...   | 0     | 0.0     | 0.0
Coconut water should not be sweetened!!!...   | 0     | 0.0     | 0.0
This will ruin supermarket mustard for y...   | 0     | 0.0     | 0.0
I have tasted one too many different mus...   | 0     | 0.0     | 0.0
A very tasty little cake. The cake was s...   | 0     | 0.0     | 0.0
The cake was a little smaller than I tho...   | 0     | 0.0     | 0.0
This tea actually tastes the way a rose ...   | 0     | 0.0     | 0.0
It says Habenero peppers on the ingredie...   | 0     | 0.0     | 0.0
Great sauce! Used in many Jamaican resta...   | 0     | 0.0     | 0.0
Tastes too sweet, which Jerk Seasoning i...   | 0     | 0.0     | 0.0
I thought I would try this, but I am sti...   | 0     | 0.0     | 0.0
Received order within 7 business days.  ...   | 1     | 0.0434  | 2.8748
I LOVE this sauce! It is sweet and molas...   | 0     | 0.0     | 0.0
I love this sauce! I used to get it at m...   | 0     | 0.0     | 0.0
We used to buy this sauce at our local g...   | 0     | 0.0     | 0.0
This sauce has just the right combinatio...   | 0     | 0.0     | 0.0
(First of all, somebody is chasing me ar...   | 0     | 0.0     | 0.0
It's not great plain, but it's wonderful...   | 0     | 0.0     | 0.0
These cloves are very finely ground and ...   | 0     | 0.0     | 0.0
This mix is probably not something you w...   | 0     | 0.0     | 0.0
When I opened the package, I expect the ...   | 0     | 0.0     | 0.0
this is the best halal beef jerky i have...   | 0     | 0.0     | 0.0
I am not Muslim, but was interested in t...   | 0     | 0.0     | 0.0
Well, after trying a lot of brands, this...   | 0     | 0.0     | 0.0
Great product and it tastes great.  I ke...   | 0     | 0.0     | 0.0
These are very tasty, but way too sweet ...   | 0     | 0.0     | 0.0
Never had jerky before because I've neve...   | 0     | 0.0     | 0.0
amazing taste, incredible quality. This ...   | 0     | 0.0     | 0.0
I don't eat chips often, but when I do, ...   | 0     | 0.0     | 0.0
Product arrived on time, nicely packaged...   | 0     | 0.0     | 0.0
I got these for my mom who is always suc...   | 0     | 0.0     | 0.0
This oil is wonderful. I've had almond o...   | 0     | 0.0     | 0.0
I wanted to love this because I LOVE Ear...   | 0     | 0.0     | 0.0
As someone who goes through lots of thym...   | 0     | 0.0     | 0.0
Good product and reasonable price compar...   | 0     | 0.0     | 0.0
I have purchased several herbs from Fron...   | 0     | 0.0     | 0.0
I was reading a news story about how lab...   | 0     | 0.0     | 0.0
I use a lot of various spices in my cook...   | 0     | 0.0     | 0.0
This is the best olive oil not for cooki...   | 0     | 0.0     | 0.0
this item came exactly as described and ...   | 0     | 0.0     | 0.0
I brought some of this back from a trip ...   | 0     | 0.0     | 0.0
I bought this on a whim and wow do I con...   | 2     | 0.1247  | 2.8336
I love jerk cooking, and this is the per...   | 0     | 0.0     | 0.0
Pamela's makes an awesome, delicious, ea...   | 0     | 0.0     | 0.0
Pamela's all purpose mix is exactly what...   | 0     | 0.0     | 0.0
I love Pamelas Baking Mix.  The 25 lb ba...   | 0     | 0.0     | 0.0
What can I say about this flour that won...   | 0     | 0.0     | 0.0
I am so excited about this product.  I h...   | 1     | 0.0628  | 0.0
I have a cafe in Talent , Oregon.  I cou...   | 0     | 0.0     | 0.0
You can exchange this baking mix for reg...   | 0     | 0.0     | 0.0
My wife has Celiac Sprue which is a Alle...   | 0     | 0.0     | 0.0
Growing up with wheat, I had an aversion...   | 0     | 0.0     | 0.0
I keep Pamela's baking mix in a 7 gallon...   | 0     | 0.0     | 0.0
This is our second time purchasing the 2...   | 0     | 0.0     | 0.0
We use this flour for pancakes, muffins,...   | 0     | 0.0     | 0.0
We go through Pamela's like crazy.  Fant...   | 0     | 0.0     | 0.0
My family and I are relatively new to gl...   | 0     | 0.0     | 0.0
This is exactly what I wanted. It is muc...   | 0     | 0.0     | 0.0
The product arrived undamaged just as it...   | 0     | 0.0     | 0.0
When you have health issues taking Glute...   | 0     | 0.0     | 0.0
What's not to like about Pamela's baking...   | 0     | 0.0     | 0.0
I've tried tons of GF pancake mixes.  I ...   | 0     | 0.0     | 0.0
It's hard to find quality gf products, a...   | 0     | 0.0     | 0.0
I started eating these after reading Ess...   | 0     | 0.0     | 0.0
I like them as a midmorning snack with a...   | 1     | 0.0346  | 0.0
If you want a quick pick me up in a smal...   | 0     | 0.0     | 0.0
Breakfast cookies are a favorite with th...   | 0     | 0.0     | 0.0
Erin Baker's products are a favorite for...   | 1     | 0.0396  | 2.3232
My kids (4yrs and 1 1/2yrs) love these c...   | 0     | 0.0     | 0.0
We LOVE Erin Baker's Breakfast Cookies.<...   | 0     | 0.0     | 0.0
These are not awful if eaten with a cup ...   | 1     | 0.026   | 1.6292
I was expecting hard tasteless healthy c...   | 0     | 0.0     | 0.0
These are excellent. They taste great an...   | 1     | 0.0748  | 0.0
I love these cookies and I love Erin as ...   | 0     | 0.0     | 0.0
I live in the area where these cookies a...   | 1     | 0.028   | 1.6126
ERIN BAKER'S ORGANIC BREAKFAST COOKIES A...   | 0     | 0.0     | 0.0
Of the Erin Baker products, the Fruit & ...   | 1     | 0.0338  | 2.0257
If you are looking for a rich chocolate ...   | 0     | 0.0     | 0.0
My kids love these, and we've ordered th...   | 0     | 0.0     | 0.0
I've been having these cookies for about...   | 0     | 0.0     | 0.0
I started out thinking they were OK, a l...   | 0     | 0.0     | 0.0
If you want to treat your tastebuds to t...   | 0     | 0.0     | 0.0
A friend brought me this from Argentina ...   | 0     | 0.0     | 0.0
I think this is the best Dulce de Leche ...   | 0     | 0.0     | 0.0
Just an outstanding product<br /><br />A...   | 0     | 0.0     | 0.0
I was born in Argentina and this is a to...   | 0     | 0.0     | 0.0
My father grew up in Argentina and since...   | 0     | 0.0     | 0.0
We used to have a pipeline to get homema...   | 0     | 0.0     | 0.0
I am so glad I ordered this; it is the b...   | 0     | 0.0     | 0.0
Very high quality dulce de leche from Ar...   | 0     | 0.0     | 0.0
I bought this for my girlfriend as she h...   | 0     | 0.0     | 0.0
This is a good quality product, which de...   | 0     | 0.0     | 0.0
I wasn't much of a tea drinker until I b...   | 0     | 0.0     | 0.0
I love tea, hot or cold, and am always l...   | 0     | 0.0     | 0.0
I think this is a really good deal. I se...   | 0     | 0.0     | 0.0
Live with digestive problems, and you ea...   | 1     | 0.015   | 1.2349
The fennel smells fresh, tastes good, an...   | 0     | 0.0     | 0.0
I love gummy bears. Love. I also love to...   | 0     | 0.0     | 0.0
These are guaranteed to be a hit with my...   | 0     | 0.0     | 0.0
My four kids LOVE these, it's great that...   | 0     | 0.0     | 0.0
These are always delicious & a much heal...   | 0     | 0.0     | 0.0
I found these little awesomely delicious...   | 0     | 0.0     | 0.0
My 18 month old grandson only eats organ...   | 0     | 0.0     | 0.0
You cant go wrong with Rosa Monte Especi...   | 0     | 0.0     | 0.0
I switched to mate from coffee a few yea...   | 5     | 0.0455  | 1.5241
Packages came in soft container that had...   | 0     | 0.0     | 0.0
Rosamonte Especial can never let you dow...   | 0     | 0.0     | 0.0
If you're setting out a whole can at onc...   | 0     | 0.0     | 0.0
I've been feeding Wellness grain free fo...   | 0     | 0.0     | 0.0
I've been on the hunt for high quality, ...   | 0     | 0.0     | 0.0
I have 5 house cats.  One was recently d...   | 0     | 0.0     | 0.0
This cat food has great, healthy ingredi...   | 0     | 0.0     | 0.0
No more dry kibble for our felines!!!  A...   | 0     | 0.0     | 0.0
I'd been feeding them Wellness until the...   | 0     | 0.0     | 0.0
This slop has the color and consistency ...   | 0     | 0.0     | 0.0
Great price and my cat loves this food. ...   | 0     | 0.0     | 0.0
I've been feeding Wellness grain-free fo...   | 0     | 0.0     | 0.0
My cats aren't usually picky and I've ha...   | 0     | 0.0     | 0.0
My youngest cat goes insane over this st...   | 0     | 0.0     | 0.0
I have the coolest different cats ever-w...   | 0     | 0.0     | 0.0
Cats do occasionally need a little green...   | 0     | 0.0     | 0.0
We recently adopted a new kitten. We rot...   | 1     | 0.0472  | 2.9172
I adopted my adorable Edmund last year f...   | 0     | 0.0     | 0.0
The consistency of the grain free chicke...   | 0     | 0.0     | 0.0
I was really hoping this grain free cann...   | 0     | 0.0     | 0.0
First off, my cats loved the food. One o...   | 0     | 0.0     | 0.0
I gave it 3 stars because of the quality...   | 0     | 0.0     | 0.0
Wonderful ingredients list but the peas ...   | 0     | 0.0     | 0.0
This Yuban DARK ROAST is outstanding.  I...   | 4     | 0.1839  | 6.9633
If you like strong coffee, this is it!  ...   | 5     | 0.2165  | 5.2442
My husband and I are always searching fo...   | 2     | 0.0543  | 0.0
Excellent.  We have enjoyed Yuban coffee...   | 6     | 0.3429  | 7.6731
Yuban makes the best cup of coffee. Eith...   | 9     | 0.2197  | 2.8104
Living in Baton Rouge my wife and I dran...   | 7     | 0.2545  | 8.3361
Yikes!  What was I thinking when I order...   | 2     | 0.0607  | 0.0
I can only say that this is great coffee...   | 1     | 0.0775  | 0.0
I was drinking Yuban Organic medium roas...   | 5     | 0.1154  | 3.121
Until recently I thought that coffee was...   | 5     | 0.1062  | 3.1838
I Wish They Hadn't Changed the Formula f...   | 4     | 0.1381  | 5.4321
We had not been able to find the Dark Ro...   | 1     | 0.1036  | 4.0831
Warning: it contains food preservatives....   | 0     | 0.0     | 0.0
I own a small night club and this is, ha...   | 0     | 0.0     | 0.0
I received a whole package of this delic...   | 0     | 0.0     | 0.0
I found these tubs at Costco and was dis...   | 0     | 0.0     | 0.0
This is definitely the best snack mix I ...   | 0     | 0.0     | 0.0
I agree with all who have said that this...   | 0     | 0.0     | 0.0
This pub mix is really a cut above your ...   | 0     | 0.0     | 0.0
I tasted this snack at my local pub and ...   | 0     | 0.0     | 0.0
Hands down, the best snack you will ever...   | 0     | 0.0     | 0.0
Enjoyed the product and they also provid...   | 0     | 0.0     | 0.0
This mix is great anytime.  I love it.  ...   | 0     | 0.0     | 0.0
I absolutely love this mix.  We keep it ...   | 0     | 0.0     | 0.0
I found this mix at the Ft Myer Commissa...   | 0     | 0.0     | 0.0
This is an addicting, fantastic snack mi...   | 0     | 0.0     | 0.0
The taste is great but it gave me a terr...   | 0     | 0.0     | 0.0
; the problem with this mix -- and to mi...   | 0     | 0.0     | 0.0
Cat grass seeds will sprout very easily-...   | 0     | 0.0     | 0.0
This is good stuff.  However, I planted ...   | 0     | 0.0     | 0.0
Cat Grass is not only a treat that cats ...   | 0     | 0.0     | 0.0
The packet of these seeds that I receive...   | 0     | 0.0     | 0.0
I've had luck with this seed and all the...   | 0     | 0.0     | 0.0
Great product.  The indoor kitties love ...   | 0     | 0.0     | 0.0
YUM, I am SO HAPPY my mom bought this de...   | 0     | 0.0     | 0.0
I use this to grow my cat grass every mo...   | 0     | 0.0     | 0.0
Cat grass, also known as wheat grass, is...   | 0     | 0.0     | 0.0
Received this product much sooner than p...   | 0     | 0.0     | 0.0
This stuff is awesome!<br /><br />Grows ...   | 0     | 0.0     | 0.0
We have been buying Cat Grass for many y...   | 0     | 0.0     | 0.0
Cat grass is cat grass, and I have one c...   | 0     | 0.0     | 0.0
So, these seeds do exactly as advertised...   | 0     | 0.0     | 0.0
I have been growing this "Cat Grass" for...   | 0     | 0.0     | 0.0
I planted this grass and in 8 days I had...   | 0     | 0.0     | 0.0
The grass sprouted quickly, with a great...   | 0     | 0.0     | 0.0
Our cats love the grass.  It's easy to g...   | 1     | 0.1011  | 4.6976
I wanted to grow some cat grass for my k...   | 0     | 0.0     | 0.0
I normally purchase already-grown contai...   | 0     | 0.0     | 0.0
These seeds grow very easy, one seed pac...   | 0     | 0.0     | 0.0
Excellent germination!  Only 4 days and ...   | 1     | 0.1101  | 4.5532
This was the only seed pack I bought of ...   | 0     | 0.0     | 0.0
Tiger loves the cat grass..It only takes...   | 0     | 0.0     | 0.0
It was so easy to grow and my cat loved ...   | 0     | 0.0     | 0.0
Unfortunately, bunnies love it, too, so ...   | 0     | 0.0     | 0.0
These seeds always grow, unlike some oth...   | 0     | 0.0     | 0.0
In less than a week, my kitties had gras...   | 0     | 0.0     | 0.0
Excellent product and price. Would do bu...   | 1     | 0.1526  | 5.1913
the true test is that our cats really lo...   | 0     | 0.0     | 0.0
I bought 4 packets and planted one of th...   | 0     | 0.0     | 0.0
My two cats must not be interested in gr...   | 0     | 0.0     | 0.0
It was hard to grow but once it grew my ...   | 0     | 0.0     | 0.0
This product is great for growing cat gr...   | 0     | 0.0     | 0.0
It got here fast, grew quickly and my ca...   | 1     | 0.0936  | 4.5185
Our cat loves to eat this grass and it w...   | 0     | 0.0     | 0.0
I have 3 cats...2 could care less..the o...   | 0     | 0.0     | 0.0
My cat love this grass. Really easy to g...   | 0     | 0.0     | 0.0
i have 3 cats here at home and they need...   | 0     | 0.0     | 0.0
Don't know why people want to step in co...   | 0     | 0.0     | 0.0
I just picked these up at random at my l...   | 2     | 0.1212  | 6.1768
Great candy! Sweet and intense, low calo...   | 1     | 0.0581  | 0.0
Japanese sweet but strong black coffee c...   | 2     | 0.0976  | 3.2965
There is nothing wrong with this product...   | 0     | 0.0     | 0.0
My cats really love this 9 Lives Seafood...   | 0     | 0.0     | 0.0
We enjoy these peanut butter and jelly b...   | 0     | 0.0     | 0.0
My 2 year old recently was diagnosed all...   | 0     | 0.0     | 0.0
I tried these bars and they were very go...   | 0     | 0.0     | 0.0
Out of all the granola bars that Bakery ...   | 0     | 0.0     | 0.0
These are good bars for being gluten fre...   | 0     | 0.0     | 0.0

### Binning and Grouping by BM25 and TF-IDF Scores

In [34]:
bm25_bins = [-0.1, 0.5, 1.0, 1.5, 2.0, df['BM25_Score'].max() + 1]
bm25_labels = ['0-0.5', '0.5-1.0', '1.0-1.5', '1.5-2.0', '>2.0']
df['BM25_Score_Bin'] = pd.cut(df['BM25_Score'], bins=bm25_bins, labels=bm25_labels, right=False)

print("BM25 Score Bin Distribution:")
print(df.groupby('BM25_Score_Bin')['BM25_Score'].count())
print("\n")

tfidf_bins = [-0.1, 0.05, 0.1, 0.15, df['TFIDF_Score'].max() + 1]
tfidf_labels = ['0-0.05', '0.05-0.1', '0.1-0.15', '>0.15']
df['TFIDF_Score_Bin'] = pd.cut(df['TFIDF_Score'], bins=tfidf_bins, labels=tfidf_labels, right=False)

print("TF-IDF Score Bin Distribution:")
print(df.groupby('TFIDF_Score_Bin')['TFIDF_Score'].count())

BM25 Score Bin Distribution:
BM25_Score_Bin
0-0.5      8271
0.5-1.0      21
1.0-1.5      64
1.5-2.0     161
>2.0       1483
Name: BM25_Score, dtype: int64


TF-IDF Score Bin Distribution:
TFIDF_Score_Bin
0-0.05      8443
0.05-0.1     899
0.1-0.15     411
>0.15        247
Name: TFIDF_Score, dtype: int64

/tmp/ipykernel_10059/2945259929.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BM25_Score_Bin'] = pd.cut(df['BM25_Score'], bins=bm25_bins, labels=bm25_labels, right=False)
/tmp/ipykernel_10059/2945259929.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('BM25_Score_Bin')['BM25_Score'].count())
/tmp/ipykernel_10059/2945259929.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TFIDF_Score_Bin'] = pd.cut(df['TFIDF_Score'], bins=tfidf_bins, labels=tfidf_labels, right=False)
/tmp/ipykernel_10059/2945259929.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('TFIDF_Score_Bin')['TFIDF_Score'].count())

### Binning and Grouping by Count Scores

In [35]:
max_count_score = df['Count_Score'].max()

# Example: 0, 1-2, 3-5, >5
if max_count_score < 1:
    count_bins = [-0.1, 0.5, max_count_score + 1]
    count_labels = ['0', '>0']
elif max_count_score < 5:
    count_bins = [x - 0.5 for x in range(int(max_count_score) + 2)]
    count_labels = [str(x) for x in range(int(max_count_score) + 1)]
else:
    # Custom bins for larger ranges
    count_bins = [-0.1, 0.5, 2.5, 5.5, max_count_score + 1]
    count_labels = ['0', '1-2', '3-5', '>5']

df['Count_Score_Bin'] = pd.cut(df['Count_Score'], bins=count_bins, labels=count_labels, right=True)

print("Count Score Bin Distribution:")
print(df.groupby('Count_Score_Bin')['Count_Score'].count())

Count Score Bin Distribution:
Count_Score_Bin
0      7857
1-2    1569
3-5     461
>5      113
Name: Count_Score, dtype: int64

/tmp/ipykernel_10059/1850792071.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Count_Score_Bin'] = pd.cut(df['Count_Score'], bins=count_bins, labels=count_labels, right=True)
/tmp/ipykernel_10059/1850792071.py:24: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('Count_Score_Bin')['Count_Score'].count())

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
words_to_test = ["delicious", "tasty", "spoiled", "coffee"]

tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(words_to_test).toarray()
tfidf_vocab = {word: tfidf_matrix[i] for i, word in enumerate(words_to_test)}

## Comparison between TFIDF and Word Embeddings

In [44]:
pairs = [("delicious", "tasty"), ("delicious", "spoiled")]

print(f"{'Word Pair':<25} | {'TF-IDF Similarity':<20}")
print("-" * 50)

for w1, w2 in pairs:
    v1_t, v2_t = tfidf_vocab[w1].reshape(1, -1), tfidf_vocab[w2].reshape(1, -1)
    sim_tfidf = cosine_similarity(v1_t, v2_t)[0][0]

    print(f"{w1 + ' <-> ' + w2:<25} | {sim_tfidf:<20.4f}")

Word Pair                 | TF-IDF Similarity
--------------------------------------------------
delicious <-> tasty       | 0.0000
delicious <-> spoiled     | 0.0000

In [48]:
!pip install gensim
import gensim.downloader as api
print("Load glove")
dense_model = api.load("glove-wiki-gigaword-50")

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.0)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 32.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0
Load glove
[==================================================] 100.0% 66.0/66.0MB downloaded

In [60]:
vocabulary = list(set([word for pair in word_pairs for word in pair]))
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(vocabulary).toarray()

tfidf_lookup = {word: tfidf_matrix[i] for i, word in enumerate(vocabulary)}

word_pairs = [
    ("delicious", "tasty"),
    ("coffee", "espresso"),
    ("delicious", "spoiled"),
    ("coffee", "software")
]

comparison_data = []

for w1, w2 in word_pairs:
    v1_tfidf = tfidf_lookup[w1].reshape(1, -1)
    v2_tfidf = tfidf_lookup[w2].reshape(1, -1)
    similarity_tfidf = cosine_similarity(v1_tfidf, v2_tfidf)[0][0]

    similarity_dense = dense_model.similarity(w1, w2)

    comparison_data.append({
        "Word 1": w1,
        "Word 2": w2,
        "TF-IDF Similarity": round(similarity_tfidf, 4),
        "Dense Embedding Similarity": round(similarity_dense, 4)
    })

# 3. Print the Structured Output Matrix
df_results = pd.DataFrame(comparison_data)
print("\n" + "="*70 + "\nMATHEMATICAL SEMANTIC SIMILARITY MATRIX\n" + "="*70)
print(df_results.to_string(index=False))

======================================================================
MATHEMATICAL SEMANTIC SIMILARITY MATRIX
======================================================================
   Word 1   Word 2  TF-IDF Similarity  Dense Embedding Similarity
delicious    tasty                0.0                      0.9297
   coffee espresso                0.0                      0.6471
delicious  spoiled                0.0                      0.5500
   coffee software                0.0                      0.3667

Dense Embedding show that here is semantic meaning behind each pair of word, TFIDF does not.